CoreWebAppMvc/CoreWebAppMvc/Models/Category.cs
namespace CoreWebAppMvc.Models;

public class Category
{
    public int Id { get; set; }

    public string Name { get; set; } = null!;

    public List<Item>? Items { get; set; }
}

CoreWebAppMvc/CoreWebAppMvc/Models/Client.cs
namespace CoreWebAppMvc.Models;

public class Client
{
    public int Id { get; set; }

    public string Name { get; set; } = null!;

    public List<ItemClient>? ItemClients { get; set; }
}

CoreWebAppMvc/CoreWebAppMvc/Models/ErrorViewModel.cs
namespace CoreWebAppMvc.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CoreWebAppMvc/CoreWebAppMvc/Models/Item.cs
using System.ComponentModel.DataAnnotations.Schema;

namespace CoreWebAppMvc.Models;

public class Item
{
    public int Id { get; set; }

    public string Name { get; set; }

    public double Price { get; set; }

    public int? SerialNumberId { get; set; }

    public SerialNumber? SerialNumber { get; set; }

    public int? CategoryId { get; set; }

    [ForeignKey("CategoryId")]
    public Category? Category { get; set; } = null!;

    public List<ItemClient>? ItemClients = null!;
}

CoreWebAppMvc/CoreWebAppMvc/Models/ItemClient.cs
namespace CoreWebAppMvc.Models;

public class ItemClient
{
    public int ItemId { get; set; }

    public Item Item { get; set; } = null!;

    public int ClientId { get; set; }

    public Client Client { get; set; } = null!;
}

CoreWebAppMvc/CoreWebAppMvc/Models/SerialNumber.cs
using System.ComponentModel.DataAnnotations.Schema;

namespace CoreWebAppMvc.Models;

public class SerialNumber
{
    public int Id { get; set; }

    public string Name { get; set; } = null!;

    public int? ItemId { get; set; }

    [ForeignKey("ItemId")]
    public Item? Item { get; set; }



}

CoreWebAppMvc/CoreWebAppMvc/Controllers/CustomController.cs
using CoreWebAppMvc.Models;
using Microsoft.AspNetCore.Mvc;

namespace CoreWebAppMvc.Controllers;

[Route("Custom")]
public class CustomController : Controller
{
    public IActionResult Index()
    {
        return View();
    }

/*
 * pass name in query param like ?name=test
 * total url will be /teja/plaincontent/44?name=test
 */
    [Route("plaincontent/{id?}")]
    public IActionResult Content(int id, string name)
    {
        return Content("Plain Content" + id + name);
    }

    [Route("razorsyntax")]
    public IActionResult RazorSyntax()
    {
        return View("myview");
    }

    [Route("overview")]
    public IActionResult Overview()
    {
        Item item = new Item() { Id = 10, Name = "Teja" };
        return View(item);
    }
}

CoreWebAppMvc/CoreWebAppMvc/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using CoreWebAppMvc.Models;

namespace CoreWebAppMvc.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

CoreWebAppMvc/CoreWebAppMvc/Controllers/ItemsController.cs
using CoreWebAppMvc.Data;
using CoreWebAppMvc.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace CoreWebAppMvc.Controllers;


public class ItemsController : Controller
{

    private readonly MyDbContext dbContext;

    public ItemsController(MyDbContext dbContext)
    {
        this.dbContext = dbContext;
    }

    public IActionResult Index()
    {
        var items = dbContext.Items.Include(i => i.SerialNumber).Include(i => i.Category).Include(i => i.ItemClients).ThenInclude(ic => ic.Client).ToList();
        return View(items);
    }

    public IActionResult Create()
    {
        ViewData["Categories"] = new SelectList(dbContext.Categories, "Id", "Name");
        return View();
    }

    [HttpPost]
    public IActionResult Create([Bind("Id, Name, Price, CategoryId")] Item item)
    {
        if (ModelState.IsValid)
        {
            dbContext.Items.Add(item);
            dbContext.SaveChanges();
            return RedirectToAction("Index");
        }
        return View();
    }


    public IActionResult Edit(int id)
    {
        ViewData["Categories"] = new SelectList(dbContext.Categories, "Id", "Name");
        Item? dbItem = dbContext.Items.Find(id);
        return View(dbItem);
    }

    [HttpPost]
    public IActionResult Edit(int id, [Bind("Id, Name, Price, CategoryId")] Item item)
    {

        if (ModelState.IsValid)
        {
            dbContext.Update(item);
            dbContext.SaveChanges();
        }
        return RedirectToAction("Index");
    }

    public IActionResult Delete(int id)
    {
        Item? item = dbContext.Items.Find(id);
        if (item != null)
        {
            dbContext.Items.Remove(item);
            dbContext.SaveChanges();
        }
        return RedirectToAction("Index");
    }
}

CoreWebAppMvc/CoreWebAppMvc/Views/Custom/Index.cshtml
<h2>Test Controller</h2>

CoreWebAppMvc/CoreWebAppMvc/Views/Custom/Overview.cshtml
@model CoreWebAppMvc.Models.Item

<p>Custom Overview Page @Model.Name</p>

CoreWebAppMvc/CoreWebAppMvc/Views/Custom/myview.cshtml
<h2>MyView</h2>

@{
    var names = new List<string> {"one", "two","three"};
}

<ul>
    @foreach(var name in names)
    {
        <li>@name</li>
    }
</ul>

CoreWebAppMvc/CoreWebAppMvc/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

CoreWebAppMvc/CoreWebAppMvc/Views/Items/Create.cshtml
@model CoreWebAppMvc.Models.Item;
@{
    ViewData["Title"] = "Create Item";
}
<h2>Create an Item</h2>

<form asp-action="Create" method="post">
    <div class="form-group">
        <label for="Name">Item Name</label>
        <input type="text" class="form-control" asp-for="Name" />
    </div>
    <label for="Price">Price</label>
    <div class="input-group">
        <div class="input-group-prepend">
            <span class="input-group-text">$</span>
        </div>
        <input type="number" class="form-control" asp-for="Price" step=".01" />
    </div>
    <div class="form-group">
        <label for="CategoryId">Category</label>
        <select class="form-control" asp-for="CategoryId" asp-items="ViewBag.Categories"></select>
    </div>
    <div class="mt-3">
        <button class="btn btn-primary" type="submit">Create</button>
        <a class="btn btn-secondary" asp-action="Index">Cancel</a>
    </div>
</form>

CoreWebAppMvc/CoreWebAppMvc/Views/Items/Edit.cshtml
@model CoreWebAppMvc.Models.Item;
@{
    ViewData["Title"] = "Edit Item";
}
<h2>Create an Item</h2>

<form asp-action="Edit" method="post">
    <div class="form-group">
        <label for="Name">Item Name</label>
        <input type="text" class="form-control" asp-for="Name" />
    </div>
    <label for="Price">Price</label>
    <div class="input-group">
        <div class="input-group-prepend">
            <span class="input-group-text">$</span>
        </div>
        <input type="number" class="form-control" asp-for="Price" step=".01"/>
    </div>
    <div class="form-group">
        <label for="CategoryId">Category</label>
        <select class="form-control" asp-for="CategoryId" asp-items="ViewBag.Categories"></select>
    </div>
    <div class="mt-3">
        <button class="btn btn-primary" type="submit">Update</button>
        <a class="btn btn-secondary" asp-action="Index">Cancel</a>
    </div>
</form>

CoreWebAppMvc/CoreWebAppMvc/Views/Items/Index.cshtml
@using CoreWebAppMvc.Models;
@model List<Item>
@{
    ViewData["Title"] = "Items List";
}
<h2>Items</h2>
<a asp-action="Create" class="btn btn-dark">Create an Item</a>
<table class="table table-striped">
    <thead>
        <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Price</th>
            <th>Serial Number(1-1)</th>
            <th>Category(1-M)</th>
            <th>Client(M-M)</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Id</td>
                <td>@item.Name</td>
                <td>$ @item.Price</td>
                <td>@item.SerialNumber?.Name</td>
                <td>@item.Category?.Name</td>
                <td>
                @foreach(var IC in item.ItemClients)
                {
                    @IC.Client?.Name
                }
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-primary">Edit</a>
                    <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>
   
    

CoreWebAppMvc/CoreWebAppMvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CoreWebAppMvc</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CoreWebAppMvc.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CoreWebAppMvc</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Items" asp-action="Index">Items Crud</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Custom" asp-action="Index">Custom Contol</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - CoreWebAppMvc - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>